### ISSUE TITLE
Windows 11: flutter:  bitsdojo_window is not initalized.  

### ISSUE THREAD

**Issue by ggwozdz90** [bitsdojo/bitsdojo_window#248]
Hello,

I have a problem with running the flutter application with your package.

My environemnt looks like this:
Windows 11 Pro 23H2 22631.3007
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.5, on Microsoft Windows [Version 10.0.22631.3007], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.8.2)
[√] Android Studio (version 2022.3)
[√] VS Code, 64-bit edition (version 1.85.1)
[√] Connected device (3 available)
[√] Network resources

Console dump:
flutter:  bitsdojo_window is not initalized.  

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: BitsDojoNotInitializedException
#0      new WinAppWindow._ (package:bitsdojo_window_windows/src/app_window.dart:24:7)
#1      WinAppWindow._instance (package:bitsdojo_window_windows/src/app_window.dart:29:54)
#2      WinAppWindow._instance (package:bitsdojo_window_windows/src/app_window.dart)
#3      new WinAppWindow (package:bitsdojo_window_windows/src/app_window.dart:16:12)
#4      BitsdojoWindowWindows.appWindow (package:bitsdojo_window_windows/src/bitsdojo_window_windows_real.dart:18:12)
#5      appWindow (package:bitsdojo_window/src/app_window.dart:42:20)
#6      main.<anonymous closure> (package:flutter_application_1/main.dart:9:5)
#7      BitsdojoWindowWindows.doWhenWindowReady.<anonymous closure> (package:bitsdojo_window_windows/src/bitsdojo_window_windows_real.dart:28:15)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:846:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:875:13)
#10     Future._completeWithValue (dart:async/future_impl.dart:647:5)
#11     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:721:7)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)

The same application can be started without any problem on Windows 10.
When I build the same application on Windows 10 machine I can run on on Windows 10 and 11.

Repo with sample:
https://github.com/ggwozdz90/flutter_bitsdojo_window_win11_issue/tree/main/flutter_application_1

Do you have any idea if it is problem with my environemnt or bug in your package?

**Comment by ajaymalah** [comment]
having same problem
