### ISSUE TITLE
Support linux 

### ISSUE THREAD

**Issue by kindlychung** [bitsdojo/bitsdojo_window#7]
Would be nice to have this work on linux!

**Comment by bitsdojo** [comment]
I will investigate this after macOS is complete 😉

**Comment by EriKWDev** [comment]
I got a crash on Linux when I tried it. Here is the error message:
```yml
[ERROR:flutter/lib/ui/ui_dart_state.cc(184)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol (/media/erikwg/Storage/Documents/Coding/GitHub/pandoceditor_flutter/build/linux/debug/bundle/[project_name]: undefined symbol: bitsdojo_window_setAppState)
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:31:29)
#1      _setAppState (package:bitsdojo_window/src/native_api.dart)
package:bitsdojo_window/src/native_api.dart:1
#2      _setAppState (package:bitsdojo_window/src/native_api.dart)
package:bitsdojo_window/src/native_api.dart:1
#3      setAppState
package:bitsdojo_window/src/native_api.dart:36
#4      doWhenWindowReady.<anonymous closure>
package:bitsdojo_window/src/app_window.dart:9
#5      _rootRunUnary (dart:async/zone.dart:1194:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1097:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:150:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:708:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:737:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:541:5)

```

**Comment by bitsdojo** [comment]
The sample app now runs on Linux but still needs some work to be on-par with Windows and macOS implementations.

**Comment by bitsdojo** [comment]
Linux support is now added in 0.0.1.

More details here: https://github.com/bitsdojo/bitsdojo_window/issues/43#issuecomment-857307042
