### ISSUE TITLE
Unhandled Exception: Invalid argument(s): Failed to lookup symbol (127)

### ISSUE THREAD

**Issue by DirtyNative** [bitsdojo/bitsdojo_window#93]
I've upgraded my flutter project to null-safety and after I wanted to run it, I ran into following issue:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol (127)
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:31:29)
#1      bitsdojoWindowAPI
package:bitsdojo_window_windows/src/native_api.dart:66
#2      bitsdojoWindowAPI (package:bitsdojo_window_windows/src/native_api.dart)
package:bitsdojo_window_windows/src/native_api.dart:1
#3      _publicAPI
package:bitsdojo_window_windows/src/native_api.dart:69
#4      _publicAPI (package:bitsdojo_window_windows/src/native_api.dart)
package:bitsdojo_window_windows/src/native_api.dart:1
#5      _setWindowCanBeShown
package:bitsdojo_window_windows/src/native_api.dart:29
#6      _setWindowCanBeShown (package:bitsdojo_window_windows/src/native_api.dart)
package:bitsdojo_window_windows/src/native_api.dart:1
#7      setWindowCanBeShown
package:bitsdojo_window_windows/src/native_api.dart:30
#8      BitsdojoWindowWindows.doWhenWindowReady.<anonymous closure>
package:bitsdojo_window_windows/src/bitsdojo_window_windows_real.dart:19
#9      _rootRunUnary (dart:async/zone.dart:1362:47)

```

which is causing the window to not appear. I can only fix it, completly removing bitsdojo_window from my project.

**Comment by bitsdojo** [comment]
Do you have a minimal repository that I can try to debug this?
